import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const opportunities = [
  // Emerging Asia (20)
  { name: "Razorpay", country: "India", region: "Emerging Asia", sector: "Fintech", opportunity_type: "pe_vc", description: "Leading Indian payment gateway processing $180B+ in TPV. Series F round open for co-investment.", deal_value_usd: 750000000, local_currency: "INR", deal_value_local: 62500000000, risk_rating: "medium", sovereign_fund_interest: ["GIC", "Temasek"], key_metrics: { gdp_growth: "6.8%", country_risk_premium: "2.1%", fx_rate: "83.2 INR/USD" } },
  { name: "Grab Financial Group", country: "Singapore", region: "Emerging Asia", sector: "Fintech", opportunity_type: "pe_vc", description: "Southeast Asia's largest super-app spinning off financial services arm.", deal_value_usd: 500000000, local_currency: "SGD", deal_value_local: 675000000, risk_rating: "low", sovereign_fund_interest: ["Temasek", "GIC"], key_metrics: { gdp_growth: "3.2%", country_risk_premium: "0.5%", fx_rate: "1.35 SGD/USD" } },
  { name: "Bukalapak", country: "Indonesia", region: "Emerging Asia", sector: "E-Commerce", opportunity_type: "cross_border_ma", description: "Indonesian e-commerce platform exploring strategic sale. 150M+ users.", deal_value_usd: 300000000, local_currency: "IDR", deal_value_local: 4650000000000, risk_rating: "high", sovereign_fund_interest: ["GIC"], key_metrics: { gdp_growth: "5.1%", country_risk_premium: "3.2%", fx_rate: "15500 IDR/USD" } },
  { name: "PhonePe Insurance", country: "India", region: "Emerging Asia", sector: "InsurTech", opportunity_type: "pe_vc", description: "Digital insurance distribution platform with 500M+ registered users.", deal_value_usd: 400000000, local_currency: "INR", deal_value_local: 33280000000, risk_rating: "medium", sovereign_fund_interest: ["GIC", "ADIA"], key_metrics: { gdp_growth: "6.8%", country_risk_premium: "2.1%", penetration_rate: "3.7%" } },
  { name: "Sea Limited Logistics", country: "Singapore", region: "Emerging Asia", sector: "Logistics", opportunity_type: "cross_border_ma", description: "Carve-out of SE Asian logistics network spanning 7 countries.", deal_value_usd: 1200000000, local_currency: "SGD", deal_value_local: 1620000000, risk_rating: "medium", sovereign_fund_interest: ["Temasek"], key_metrics: { gdp_growth: "3.2%", warehouses: "450+", countries: "7" } },
  { name: "Tata Electronics", country: "India", region: "Emerging Asia", sector: "Semiconductors", opportunity_type: "infrastructure", description: "Semiconductor fab in Gujarat with TSMC partnership.", deal_value_usd: 2800000000, local_currency: "INR", deal_value_local: 232960000000, risk_rating: "medium", sovereign_fund_interest: ["ADIA", "Mubadala"], key_metrics: { gdp_growth: "6.8%", govt_subsidy: "50%", capacity: "28nm" } },
  { name: "VNPay", country: "Vietnam", region: "Emerging Asia", sector: "Fintech", opportunity_type: "pe_vc", description: "Vietnam's dominant QR payment platform with 40M+ users.", deal_value_usd: 250000000, local_currency: "VND", deal_value_local: 6125000000000, risk_rating: "medium", sovereign_fund_interest: ["GIC"], key_metrics: { gdp_growth: "6.5%", country_risk_premium: "3.5%", fx_rate: "24500 VND/USD" } },
  { name: "Tokopedia SME Lending", country: "Indonesia", region: "Emerging Asia", sector: "Fintech", opportunity_type: "pe_vc", description: "SME lending platform embedded in Indonesia's largest marketplace.", deal_value_usd: 180000000, local_currency: "IDR", deal_value_local: 2790000000000, risk_rating: "high", sovereign_fund_interest: [], key_metrics: { gdp_growth: "5.1%", sme_gap: "$80B", npl_rate: "2.8%" } },
  { name: "Flipkart Health+", country: "India", region: "Emerging Asia", sector: "HealthTech", opportunity_type: "pe_vc", description: "Digital pharmacy and telehealth subsidiary of Flipkart.", deal_value_usd: 350000000, local_currency: "INR", deal_value_local: 29120000000, risk_rating: "medium", sovereign_fund_interest: ["Temasek", "GIC"], key_metrics: { gdp_growth: "6.8%", market_size: "$50B", digital_penetration: "8%" } },
  { name: "Akulaku", country: "Indonesia", region: "Emerging Asia", sector: "Fintech", opportunity_type: "pe_vc", description: "Digital bank and BNPL platform across Southeast Asia.", deal_value_usd: 200000000, local_currency: "IDR", deal_value_local: 3100000000000, risk_rating: "high", sovereign_fund_interest: [], key_metrics: { gdp_growth: "5.1%", users: "8M+", markets: "4" } },
  { name: "Mynt (GCash)", country: "Philippines", region: "Emerging Asia", sector: "Fintech", opportunity_type: "pe_vc", description: "Philippines' leading mobile wallet with 90M+ registered users.", deal_value_usd: 600000000, local_currency: "PHP", deal_value_local: 33600000000, risk_rating: "medium", sovereign_fund_interest: ["GIC", "Warburg Pincus"], key_metrics: { gdp_growth: "5.8%", mobile_penetration: "78%", unbanked: "56%" } },
  { name: "Cainiao Smart Logistics", country: "China", region: "Emerging Asia", sector: "Logistics", opportunity_type: "cross_border_ma", description: "Alibaba logistics spinoff with global cross-border delivery network.", deal_value_usd: 3500000000, local_currency: "CNY", deal_value_local: 25200000000, risk_rating: "high", sovereign_fund_interest: ["GIC", "Temasek"], key_metrics: { gdp_growth: "4.6%", parcels_daily: "15M+", countries: "50+" } },
  { name: "Pine Labs", country: "India", region: "Emerging Asia", sector: "Fintech", opportunity_type: "pe_vc", description: "Merchant commerce platform processing $50B+ annually. Pre-IPO round.", deal_value_usd: 450000000, local_currency: "INR", deal_value_local: 37440000000, risk_rating: "low", sovereign_fund_interest: ["Temasek", "Mubadala"], key_metrics: { gdp_growth: "6.8%", tpv: "$50B+", merchants: "500K+" } },
  { name: "GoTo Financial", country: "Indonesia", region: "Emerging Asia", sector: "Fintech", opportunity_type: "cross_border_ma", description: "Financial services arm of Indonesia's GoTo Group exploring strategic investors.", deal_value_usd: 800000000, local_currency: "IDR", deal_value_local: 12400000000000, risk_rating: "high", sovereign_fund_interest: ["ADIA"], key_metrics: { gdp_growth: "5.1%", users: "55M", lending_book: "$1.2B" } },
  { name: "Zerodha International", country: "India", region: "Emerging Asia", sector: "Fintech", opportunity_type: "pe_vc", description: "India's largest discount brokerage expanding to SE Asia and Middle East.", deal_value_usd: 500000000, local_currency: "INR", deal_value_local: 41600000000, risk_rating: "medium", sovereign_fund_interest: ["GIC"], key_metrics: { gdp_growth: "6.8%", retail_accounts: "15M+", market_share: "18%" } },
  { name: "Ninja Van", country: "Singapore", region: "Emerging Asia", sector: "Logistics", opportunity_type: "pe_vc", description: "Last-mile logistics across 6 SE Asian markets.", deal_value_usd: 300000000, local_currency: "SGD", deal_value_local: 405000000, risk_rating: "medium", sovereign_fund_interest: ["GIC"], key_metrics: { gdp_growth: "3.2%", parcels_daily: "3M+", countries: "6" } },
  { name: "Vedantu", country: "India", region: "Emerging Asia", sector: "EdTech", opportunity_type: "distressed", description: "Online tutoring platform at discounted valuation after sector correction.", deal_value_usd: 80000000, local_currency: "INR", deal_value_local: 6656000000, risk_rating: "high", sovereign_fund_interest: [], key_metrics: { gdp_growth: "6.8%", discount_to_peak: "70%", students: "35M+" } },
  { name: "Traveloka", country: "Indonesia", region: "Emerging Asia", sector: "Travel", opportunity_type: "pe_vc", description: "SE Asia's leading OTA with recovery to pre-COVID levels.", deal_value_usd: 400000000, local_currency: "IDR", deal_value_local: 6200000000000, risk_rating: "medium", sovereign_fund_interest: ["GIC"], key_metrics: { gdp_growth: "5.1%", users: "100M+", markets: "5" } },
  { name: "J&T Express", country: "China", region: "Emerging Asia", sector: "Logistics", opportunity_type: "cross_border_ma", description: "Cross-border express delivery connecting China with SE Asia.", deal_value_usd: 1500000000, local_currency: "CNY", deal_value_local: 10800000000, risk_rating: "medium", sovereign_fund_interest: ["Temasek"], key_metrics: { gdp_growth: "4.6%", parcels_daily: "10M+", countries: "13" } },
  { name: "Dream11", country: "India", region: "Emerging Asia", sector: "Gaming", opportunity_type: "pe_vc", description: "India's largest fantasy sports platform with 200M+ users. Pre-IPO.", deal_value_usd: 700000000, local_currency: "INR", deal_value_local: 58240000000, risk_rating: "medium", sovereign_fund_interest: ["Mubadala", "ADIA"], key_metrics: { gdp_growth: "6.8%", users: "200M+", revenue_growth: "45%" } },

  // MENA (15)
  { name: "NEOM Bay Development", country: "Saudi Arabia", region: "MENA", sector: "Real Estate", opportunity_type: "infrastructure", description: "Mixed-use waterfront development within NEOM. Phase 2 co-investment opportunity.", deal_value_usd: 5000000000, local_currency: "SAR", deal_value_local: 18750000000, risk_rating: "high", sovereign_fund_interest: ["PIF"], key_metrics: { gdp_growth: "4.2%", vision_2030: "Yes", fx_rate: "3.75 SAR/USD" } },
  { name: "Tabby", country: "UAE", region: "MENA", sector: "Fintech", opportunity_type: "pe_vc", description: "MENA's largest BNPL platform operating across UAE, Saudi, and Egypt.", deal_value_usd: 200000000, local_currency: "AED", deal_value_local: 734000000, risk_rating: "medium", sovereign_fund_interest: ["Mubadala"], key_metrics: { gdp_growth: "3.8%", users: "10M+", tpv: "$7B" } },
  { name: "Kitopi", country: "UAE", region: "MENA", sector: "FoodTech", opportunity_type: "distressed", description: "Cloud kitchen operator restructuring after rapid expansion. Assets at 40% discount.", deal_value_usd: 120000000, local_currency: "AED", deal_value_local: 440880000, risk_rating: "very_high", sovereign_fund_interest: [], key_metrics: { gdp_growth: "3.8%", discount: "40%", kitchens: "200+" } },
  { name: "Tamara", country: "Saudi Arabia", region: "MENA", sector: "Fintech", opportunity_type: "pe_vc", description: "Saudi BNPL unicorn with exclusive Aramco partnership.", deal_value_usd: 340000000, local_currency: "SAR", deal_value_local: 1275000000, risk_rating: "medium", sovereign_fund_interest: ["PIF", "Sanabil"], key_metrics: { gdp_growth: "4.2%", merchants: "30K+", gmv: "$3B" } },
  { name: "Fawry Digital Banking", country: "Egypt", region: "MENA", sector: "Fintech", opportunity_type: "pe_vc", description: "Egypt's leading digital payments infrastructure pivoting to neobanking.", deal_value_usd: 150000000, local_currency: "EGP", deal_value_local: 7350000000, risk_rating: "high", sovereign_fund_interest: ["ADQ"], key_metrics: { gdp_growth: "3.5%", country_risk_premium: "8.5%", unbanked: "67%" } },
  { name: "M-Pesa Africa Expansion", country: "Kenya", region: "MENA", sector: "Fintech", opportunity_type: "swf_coinvest", description: "Vodacom/Safaricom JV expanding mobile money to West Africa.", deal_value_usd: 400000000, local_currency: "KES", deal_value_local: 61600000000, risk_rating: "high", sovereign_fund_interest: ["ADIA", "CDC Group"], key_metrics: { gdp_growth: "5.0%", mobile_money_users: "50M+", markets: "7" } },
  { name: "Red Sea Global Hotels", country: "Saudi Arabia", region: "MENA", sector: "Hospitality", opportunity_type: "infrastructure", description: "Luxury resort portfolio on Saudi Red Sea coast. 16 hotel co-investment.", deal_value_usd: 2200000000, local_currency: "SAR", deal_value_local: 8250000000, risk_rating: "high", sovereign_fund_interest: ["PIF"], key_metrics: { gdp_growth: "4.2%", rooms: "3000+", completion: "2027" } },
  { name: "Careem Everything App", country: "UAE", region: "MENA", sector: "Super App", opportunity_type: "pe_vc", description: "Uber-owned MENA super app seeking minority growth equity.", deal_value_usd: 300000000, local_currency: "AED", deal_value_local: 1101000000, risk_rating: "medium", sovereign_fund_interest: ["Mubadala"], key_metrics: { gdp_growth: "3.8%", users: "50M+", services: "8" } },
  { name: "Flutterwave Africa", country: "Nigeria", region: "MENA", sector: "Fintech", opportunity_type: "pe_vc", description: "Pan-African payment infrastructure processing $20B+ annually.", deal_value_usd: 250000000, local_currency: "NGN", deal_value_local: 375000000000, risk_rating: "very_high", sovereign_fund_interest: [], key_metrics: { gdp_growth: "2.9%", country_risk_premium: "9.2%", tpv: "$20B+" } },
  { name: "ACWA Power Renewables", country: "Saudi Arabia", region: "MENA", sector: "Energy", opportunity_type: "infrastructure", description: "Solar + wind portfolio across MENA. 15GW capacity expansion.", deal_value_usd: 3500000000, local_currency: "SAR", deal_value_local: 13125000000, risk_rating: "medium", sovereign_fund_interest: ["PIF", "Mubadala"], key_metrics: { gdp_growth: "4.2%", capacity_gw: "15", irr_target: "12%" } },
  { name: "Chipper Cash", country: "Nigeria", region: "MENA", sector: "Fintech", opportunity_type: "distressed", description: "African cross-border payments at 60% valuation discount.", deal_value_usd: 80000000, local_currency: "NGN", deal_value_local: 120000000000, risk_rating: "very_high", sovereign_fund_interest: [], key_metrics: { gdp_growth: "2.9%", discount_to_peak: "60%", users: "5M+" } },
  { name: "Pure Harvest Smart Farms", country: "UAE", region: "MENA", sector: "AgriTech", opportunity_type: "pe_vc", description: "Climate-controlled farming technology for arid regions.", deal_value_usd: 180000000, local_currency: "AED", deal_value_local: 661200000, risk_rating: "medium", sovereign_fund_interest: ["ADQ", "Mubadala"], key_metrics: { gdp_growth: "3.8%", yield_multiplier: "10x", water_savings: "95%" } },
  { name: "stc Pay", country: "Saudi Arabia", region: "MENA", sector: "Fintech", opportunity_type: "pe_vc", description: "Saudi Telecom's digital wallet subsidiary pursuing banking license.", deal_value_usd: 500000000, local_currency: "SAR", deal_value_local: 1875000000, risk_rating: "low", sovereign_fund_interest: ["PIF"], key_metrics: { gdp_growth: "4.2%", users: "12M+", banking_license: "Pending" } },
  { name: "OPay", country: "Nigeria", region: "MENA", sector: "Fintech", opportunity_type: "pe_vc", description: "Nigeria's dominant mobile payment platform backed by Opera.", deal_value_usd: 400000000, local_currency: "NGN", deal_value_local: 600000000000, risk_rating: "very_high", sovereign_fund_interest: [], key_metrics: { gdp_growth: "2.9%", tpv: "$15B", market_share: "60%" } },
  { name: "Halan", country: "Egypt", region: "MENA", sector: "Fintech", opportunity_type: "pe_vc", description: "Egyptian super-app for mass market financial services and ride-hailing.", deal_value_usd: 120000000, local_currency: "EGP", deal_value_local: 5880000000, risk_rating: "high", sovereign_fund_interest: ["ADIA"], key_metrics: { gdp_growth: "3.5%", users: "7M+", services: "5" } },

  // LATAM (15)
  { name: "Kavak", country: "Mexico", region: "LATAM", sector: "Automotive", opportunity_type: "distressed", description: "Used car marketplace at 75% discount to peak valuation. Restructuring with path to profitability.", deal_value_usd: 400000000, local_currency: "MXN", deal_value_local: 6800000000, risk_rating: "high", sovereign_fund_interest: [], key_metrics: { gdp_growth: "3.2%", discount_to_peak: "75%", units_sold: "100K+/yr" } },
  { name: "Nubank Mexico", country: "Mexico", region: "LATAM", sector: "Fintech", opportunity_type: "pe_vc", description: "Nu Holdings' Mexican subsidiary growth equity round.", deal_value_usd: 600000000, local_currency: "MXN", deal_value_local: 10200000000, risk_rating: "medium", sovereign_fund_interest: ["GIC", "Temasek"], key_metrics: { gdp_growth: "3.2%", customers: "8M+", growth_rate: "120%" } },
  { name: "Mercado Libre Logistics", country: "Brazil", region: "LATAM", sector: "Logistics", opportunity_type: "infrastructure", description: "LATAM e-commerce leader expanding fulfillment network. JV opportunity.", deal_value_usd: 1500000000, local_currency: "BRL", deal_value_local: 7500000000, risk_rating: "medium", sovereign_fund_interest: ["GIC"], key_metrics: { gdp_growth: "2.9%", fulfillment_centers: "30+", same_day_coverage: "60%" } },
  { name: "Rappi Financial", country: "Colombia", region: "LATAM", sector: "Fintech", opportunity_type: "pe_vc", description: "Super-app's financial services spinoff with digital banking license.", deal_value_usd: 250000000, local_currency: "COP", deal_value_local: 1000000000000, risk_rating: "high", sovereign_fund_interest: [], key_metrics: { gdp_growth: "1.5%", users: "40M+", credit_book: "$500M" } },
  { name: "Solinftec", country: "Brazil", region: "LATAM", sector: "AgriTech", opportunity_type: "pe_vc", description: "AI-powered precision agriculture platform. 25M+ hectares under management.", deal_value_usd: 200000000, local_currency: "BRL", deal_value_local: 1000000000, risk_rating: "medium", sovereign_fund_interest: ["Mubadala"], key_metrics: { gdp_growth: "2.9%", hectares: "25M+", yield_improvement: "15%" } },
  { name: "Betterfly", country: "Chile", region: "LATAM", sector: "InsurTech", opportunity_type: "pe_vc", description: "LATAM's first impact InsurTech unicorn expanding to 10 markets.", deal_value_usd: 150000000, local_currency: "CLP", deal_value_local: 142500000000, risk_rating: "medium", sovereign_fund_interest: [], key_metrics: { gdp_growth: "2.1%", markets: "10", users: "5M+" } },
  { name: "Nearshore Manufacturing Hub", country: "Mexico", region: "LATAM", sector: "Manufacturing", opportunity_type: "infrastructure", description: "Industrial park development for US nearshoring demand in Monterrey.", deal_value_usd: 800000000, local_currency: "MXN", deal_value_local: 13600000000, risk_rating: "medium", sovereign_fund_interest: ["ADIA", "GIC"], key_metrics: { gdp_growth: "3.2%", nearshoring_growth: "35%", occupancy: "94%" } },
  { name: "Creditas", country: "Brazil", region: "LATAM", sector: "Fintech", opportunity_type: "pe_vc", description: "Brazilian secured lending fintech. $3B+ loan book.", deal_value_usd: 350000000, local_currency: "BRL", deal_value_local: 1750000000, risk_rating: "medium", sovereign_fund_interest: ["Temasek"], key_metrics: { gdp_growth: "2.9%", loan_book: "$3B+", npl: "1.8%" } },
  { name: "NotCo", country: "Chile", region: "LATAM", sector: "FoodTech", opportunity_type: "pe_vc", description: "AI-powered plant-based food company with Kraft Heinz JV.", deal_value_usd: 200000000, local_currency: "CLP", deal_value_local: 190000000000, risk_rating: "medium", sovereign_fund_interest: [], key_metrics: { gdp_growth: "2.1%", revenue_growth: "80%", markets: "8" } },
  { name: "Globant Ventures", country: "Argentina", region: "LATAM", sector: "Technology", opportunity_type: "pe_vc", description: "Corporate venture arm of LATAM's top tech company.", deal_value_usd: 100000000, local_currency: "ARS", deal_value_local: 85000000000, risk_rating: "very_high", sovereign_fund_interest: [], key_metrics: { gdp_growth: "-1.5%", country_risk_premium: "15%", tech_talent_cost: "-60% vs US" } },
  { name: "Clip", country: "Mexico", region: "LATAM", sector: "Fintech", opportunity_type: "pe_vc", description: "Mexican POS and payments platform for SMEs.", deal_value_usd: 250000000, local_currency: "MXN", deal_value_local: 4250000000, risk_rating: "medium", sovereign_fund_interest: ["GIC"], key_metrics: { gdp_growth: "3.2%", merchants: "500K+", tpv: "$8B" } },
  { name: "Bitso", country: "Mexico", region: "LATAM", sector: "Crypto", opportunity_type: "pe_vc", description: "LATAM's largest crypto exchange with cross-border remittance focus.", deal_value_usd: 300000000, local_currency: "MXN", deal_value_local: 5100000000, risk_rating: "high", sovereign_fund_interest: [], key_metrics: { gdp_growth: "3.2%", users: "8M+", remittance_volume: "$3B" } },
  { name: "Pomelo", country: "Argentina", region: "LATAM", sector: "Fintech", opportunity_type: "pe_vc", description: "Card issuing and processing infrastructure for LATAM fintechs.", deal_value_usd: 120000000, local_currency: "ARS", deal_value_local: 102000000000, risk_rating: "high", sovereign_fund_interest: [], key_metrics: { gdp_growth: "-1.5%", cards_issued: "10M+", clients: "200+" } },
  { name: "Konfio", country: "Mexico", region: "LATAM", sector: "Fintech", opportunity_type: "pe_vc", description: "Mexican SME neobank with $2B+ loan originations.", deal_value_usd: 200000000, local_currency: "MXN", deal_value_local: 3400000000, risk_rating: "medium", sovereign_fund_interest: ["GIC"], key_metrics: { gdp_growth: "3.2%", originations: "$2B+", npl: "3.2%" } },
  { name: "dLocal", country: "Uruguay", region: "LATAM", sector: "Fintech", opportunity_type: "cross_border_ma", description: "Cross-border payments processor exploring take-private.", deal_value_usd: 2000000000, local_currency: "UYU", deal_value_local: 78000000000, risk_rating: "medium", sovereign_fund_interest: ["GIC", "Temasek"], key_metrics: { gdp_growth: "2.5%", tpv: "$18B", markets: "40" } },

  // Europe (15)
  { name: "Revolut Business", country: "United Kingdom", region: "Europe", sector: "Fintech", opportunity_type: "pe_vc", description: "B2B fintech arm of Revolut seeking dedicated growth equity.", deal_value_usd: 800000000, local_currency: "GBP", deal_value_local: 640000000, risk_rating: "low", sovereign_fund_interest: ["GIC", "Mubadala"], key_metrics: { gdp_growth: "1.2%", business_accounts: "500K+", revenue: "$500M+" } },
  { name: "Northvolt", country: "Sweden", region: "Europe", sector: "CleanTech", opportunity_type: "distressed", description: "European battery gigafactory restructuring. Assets at significant discount.", deal_value_usd: 1500000000, local_currency: "SEK", deal_value_local: 15750000000, risk_rating: "very_high", sovereign_fund_interest: ["PIF"], key_metrics: { gdp_growth: "0.8%", discount_to_peak: "80%", capacity_gwh: "60" } },
  { name: "Celonis", country: "Germany", region: "Europe", sector: "Enterprise SaaS", opportunity_type: "pe_vc", description: "Process mining leader with $1B+ ARR. Late-stage round.", deal_value_usd: 1000000000, local_currency: "EUR", deal_value_local: 920000000, risk_rating: "low", sovereign_fund_interest: ["GIC", "ADIA"], key_metrics: { gdp_growth: "0.3%", arr: "$1B+", nrr: "130%" } },
  { name: "Klarna", country: "Sweden", region: "Europe", sector: "Fintech", opportunity_type: "pe_vc", description: "Pre-IPO secondary shares available at post-correction valuation.", deal_value_usd: 500000000, local_currency: "SEK", deal_value_local: 5250000000, risk_rating: "medium", sovereign_fund_interest: ["GIC"], key_metrics: { gdp_growth: "0.8%", gmv: "$90B", profitable: "Yes" } },
  { name: "Personio", country: "Germany", region: "Europe", sector: "HR Tech", opportunity_type: "pe_vc", description: "European HR platform for SMEs. Series F.", deal_value_usd: 400000000, local_currency: "EUR", deal_value_local: 368000000, risk_rating: "low", sovereign_fund_interest: ["GIC"], key_metrics: { gdp_growth: "0.3%", customers: "12K+", arr: "$300M+" } },
  { name: "UK Retail Portfolio", country: "United Kingdom", region: "Europe", sector: "Real Estate", opportunity_type: "distressed", description: "Portfolio of 40 high-street retail properties. Receiver sale.", deal_value_usd: 350000000, local_currency: "GBP", deal_value_local: 280000000, risk_rating: "high", sovereign_fund_interest: [], key_metrics: { gdp_growth: "1.2%", discount: "45%", occupancy: "72%", properties: "40" } },
  { name: "H2 Green Steel", country: "Sweden", region: "Europe", sector: "CleanTech", opportunity_type: "infrastructure", description: "Green hydrogen-powered steel plant. First-of-kind in Europe.", deal_value_usd: 3000000000, local_currency: "SEK", deal_value_local: 31500000000, risk_rating: "high", sovereign_fund_interest: ["GIC", "ADIA"], key_metrics: { gdp_growth: "0.8%", capacity_mt: "2.5", co2_reduction: "95%" } },
  { name: "Checkout.com", country: "United Kingdom", region: "Europe", sector: "Fintech", opportunity_type: "pe_vc", description: "Enterprise payments at adjusted valuation. Secondary available.", deal_value_usd: 400000000, local_currency: "GBP", deal_value_local: 320000000, risk_rating: "medium", sovereign_fund_interest: ["GIC", "Temasek"], key_metrics: { gdp_growth: "1.2%", tpv: "$250B+", profitable: "Yes" } },
  { name: "Lilium", country: "Germany", region: "Europe", sector: "Aerospace", opportunity_type: "distressed", description: "eVTOL air taxi manufacturer post-restructuring. Rescue financing.", deal_value_usd: 200000000, local_currency: "EUR", deal_value_local: 184000000, risk_rating: "very_high", sovereign_fund_interest: ["PIF"], key_metrics: { gdp_growth: "0.3%", certification: "2026", pre_orders: "700+" } },
  { name: "Wefox", country: "Germany", region: "Europe", sector: "InsurTech", opportunity_type: "distressed", description: "InsurTech restructuring. Technology platform at 65% discount.", deal_value_usd: 250000000, local_currency: "EUR", deal_value_local: 230000000, risk_rating: "very_high", sovereign_fund_interest: [], key_metrics: { gdp_growth: "0.3%", discount_to_peak: "65%", gwp: "$800M" } },
  { name: "Einride", country: "Sweden", region: "Europe", sector: "Logistics", opportunity_type: "pe_vc", description: "Autonomous electric freight transport. Series C.", deal_value_usd: 200000000, local_currency: "SEK", deal_value_local: 2100000000, risk_rating: "high", sovereign_fund_interest: ["Temasek"], key_metrics: { gdp_growth: "0.8%", routes: "500+", co2_saved: "90%" } },
  { name: "SumUp", country: "United Kingdom", region: "Europe", sector: "Fintech", opportunity_type: "pe_vc", description: "European SME payments platform with 4M+ merchants.", deal_value_usd: 600000000, local_currency: "GBP", deal_value_local: 480000000, risk_rating: "low", sovereign_fund_interest: ["GIC"], key_metrics: { gdp_growth: "1.2%", merchants: "4M+", markets: "36" } },
  { name: "ContentSquare", country: "France", region: "Europe", sector: "Enterprise SaaS", opportunity_type: "pe_vc", description: "Digital experience analytics platform. Pre-IPO.", deal_value_usd: 400000000, local_currency: "EUR", deal_value_local: 368000000, risk_rating: "low", sovereign_fund_interest: ["GIC"], key_metrics: { gdp_growth: "0.9%", arr: "$200M+", customers: "1300+" } },
  { name: "Vinted", country: "Lithuania", region: "Europe", sector: "E-Commerce", opportunity_type: "pe_vc", description: "Europe's largest secondhand marketplace. Profitable.", deal_value_usd: 350000000, local_currency: "EUR", deal_value_local: 322000000, risk_rating: "low", sovereign_fund_interest: [], key_metrics: { gdp_growth: "2.1%", users: "80M+", profitable: "Yes" } },
  { name: "Nordic Semiconductor Foundry", country: "Norway", region: "Europe", sector: "Semiconductors", opportunity_type: "infrastructure", description: "European chip sovereignty initiative. Government-backed fab.", deal_value_usd: 4000000000, local_currency: "NOK", deal_value_local: 42000000000, risk_rating: "medium", sovereign_fund_interest: ["NBIM", "GIC"], key_metrics: { gdp_growth: "1.5%", govt_backing: "40%", node: "12nm" } },

  // Frontier (15)
  { name: "VinFast Supplier Park", country: "Vietnam", region: "Frontier", sector: "Manufacturing", opportunity_type: "infrastructure", description: "Tier-1 auto parts supplier park adjacent to VinFast factory.", deal_value_usd: 500000000, local_currency: "VND", deal_value_local: 12250000000000, risk_rating: "high", sovereign_fund_interest: ["GIC"], key_metrics: { gdp_growth: "6.5%", country_risk_premium: "3.5%", fdi_growth: "25%" } },
  { name: "bKash Digital Bank", country: "Bangladesh", region: "Frontier", sector: "Fintech", opportunity_type: "pe_vc", description: "Bangladesh's dominant mobile financial services platform. 70M+ accounts.", deal_value_usd: 250000000, local_currency: "BDT", deal_value_local: 27500000000, risk_rating: "high", sovereign_fund_interest: [], key_metrics: { gdp_growth: "6.0%", accounts: "70M+", transactions_daily: "12M" } },
  { name: "Infinity Solar Egypt", country: "Egypt", region: "Frontier", sector: "Energy", opportunity_type: "infrastructure", description: "1.5GW solar farm in Upper Egypt with 25-year PPA.", deal_value_usd: 1800000000, local_currency: "EGP", deal_value_local: 88200000000, risk_rating: "high", sovereign_fund_interest: ["ADIA", "PIF"], key_metrics: { gdp_growth: "3.5%", capacity_gw: "1.5", ppa_years: "25", irr: "14%" } },
  { name: "FPT Software", country: "Vietnam", region: "Frontier", sector: "Technology", opportunity_type: "cross_border_ma", description: "Vietnam's largest IT services company exploring international strategic partner.", deal_value_usd: 2000000000, local_currency: "VND", deal_value_local: 49000000000000, risk_rating: "medium", sovereign_fund_interest: ["GIC", "Temasek"], key_metrics: { gdp_growth: "6.5%", employees: "50K+", revenue: "$2B+", markets: "30" } },
  { name: "Pathao", country: "Bangladesh", region: "Frontier", sector: "Super App", opportunity_type: "pe_vc", description: "Bangladesh super-app: ride-hailing, food delivery, payments.", deal_value_usd: 80000000, local_currency: "BDT", deal_value_local: 8800000000, risk_rating: "very_high", sovereign_fund_interest: [], key_metrics: { gdp_growth: "6.0%", rides_daily: "300K+", cities: "15" } },
  { name: "DBL Group Textiles", country: "Bangladesh", region: "Frontier", sector: "Manufacturing", opportunity_type: "cross_border_ma", description: "Vertically integrated textile manufacturer. H&M and Zara supplier.", deal_value_usd: 350000000, local_currency: "BDT", deal_value_local: 38500000000, risk_rating: "medium", sovereign_fund_interest: [], key_metrics: { gdp_growth: "6.0%", revenue: "$800M", employees: "35K", clients: "H&M, Zara, Uniqlo" } },
  { name: "AMEA Power", country: "UAE", region: "Frontier", sector: "Energy", opportunity_type: "infrastructure", description: "Renewable energy developer across Africa. 2GW pipeline.", deal_value_usd: 700000000, local_currency: "AED", deal_value_local: 2570300000, risk_rating: "high", sovereign_fund_interest: ["ADIA", "Mubadala"], key_metrics: { pipeline_gw: "2.0", countries: "15", irr_target: "15%" } },
  { name: "MoMo Vietnam", country: "Vietnam", region: "Frontier", sector: "Fintech", opportunity_type: "pe_vc", description: "Vietnam's largest e-wallet with 35M+ users. Series E.", deal_value_usd: 300000000, local_currency: "VND", deal_value_local: 7350000000000, risk_rating: "medium", sovereign_fund_interest: ["GIC"], key_metrics: { gdp_growth: "6.5%", users: "35M+", tpv: "$15B" } },
  { name: "Daraz (Alibaba SE Asia)", country: "Bangladesh", region: "Frontier", sector: "E-Commerce", opportunity_type: "cross_border_ma", description: "Alibaba divesting South Asian e-commerce operations.", deal_value_usd: 200000000, local_currency: "BDT", deal_value_local: 22000000000, risk_rating: "high", sovereign_fund_interest: [], key_metrics: { gdp_growth: "6.0%", gmv: "$1B+", users: "30M+" } },
  { name: "Orascom Construction", country: "Egypt", region: "Frontier", sector: "Infrastructure", opportunity_type: "infrastructure", description: "Major infrastructure contractor. New Administrative Capital projects.", deal_value_usd: 500000000, local_currency: "EGP", deal_value_local: 24500000000, risk_rating: "high", sovereign_fund_interest: ["ADQ"], key_metrics: { gdp_growth: "3.5%", backlog: "$8B", projects: "50+" } },
  { name: "Masan Group Consumer", country: "Vietnam", region: "Frontier", sector: "Consumer", opportunity_type: "pe_vc", description: "Vietnam's largest consumer conglomerate. Retail + FMCG spinoff.", deal_value_usd: 800000000, local_currency: "VND", deal_value_local: 19600000000000, risk_rating: "medium", sovereign_fund_interest: ["GIC", "Temasek"], key_metrics: { gdp_growth: "6.5%", stores: "3500+", market_share: "25%" } },
  { name: "Egyptian Fintech Hub", country: "Egypt", region: "Frontier", sector: "Fintech", opportunity_type: "pe_vc", description: "Central Bank-backed fintech accelerator portfolio investment.", deal_value_usd: 100000000, local_currency: "EGP", deal_value_local: 4900000000, risk_rating: "high", sovereign_fund_interest: ["ADQ"], key_metrics: { gdp_growth: "3.5%", startups: "25", unbanked: "67%" } },
  { name: "Tiki Corporation", country: "Vietnam", region: "Frontier", sector: "E-Commerce", opportunity_type: "distressed", description: "Vietnamese e-commerce at discounted valuation. Strategic sale.", deal_value_usd: 150000000, local_currency: "VND", deal_value_local: 3675000000000, risk_rating: "high", sovereign_fund_interest: [], key_metrics: { gdp_growth: "6.5%", discount_to_peak: "70%", users: "20M+" } },
  { name: "Grameenphone Digital", country: "Bangladesh", region: "Frontier", sector: "Telecom", opportunity_type: "pe_vc", description: "Telenor subsidiary's digital services arm. 85M subscribers.", deal_value_usd: 400000000, local_currency: "BDT", deal_value_local: 44000000000, risk_rating: "medium", sovereign_fund_interest: ["GIC"], key_metrics: { gdp_growth: "6.0%", subscribers: "85M", arpu: "$2.5" } },
  { name: "Long Son Petrochemicals", country: "Vietnam", region: "Frontier", sector: "Chemicals", opportunity_type: "infrastructure", description: "Vietnam's first integrated petrochemical complex. Thai partnership.", deal_value_usd: 5200000000, local_currency: "VND", deal_value_local: 127400000000000, risk_rating: "high", sovereign_fund_interest: ["GIC"], key_metrics: { gdp_growth: "6.5%", capacity_mt: "3.2", completion: "2027" } },
];

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const sb = createClient(supabaseUrl, serviceKey);

    // Check if data already exists
    const { count } = await sb.from("global_opportunities").select("id", { count: "exact", head: true });
    if ((count ?? 0) > 0) {
      return new Response(JSON.stringify({ message: `Already seeded with ${count} opportunities` }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const rows = opportunities.map((o) => ({
      name: o.name,
      country: o.country,
      region: o.region,
      sector: o.sector,
      opportunity_type: o.opportunity_type,
      description: o.description,
      deal_value_usd: o.deal_value_usd,
      local_currency: o.local_currency,
      deal_value_local: o.deal_value_local,
      risk_rating: o.risk_rating,
      sovereign_fund_interest: o.sovereign_fund_interest,
      key_metrics: o.key_metrics,
      status: "active",
      stage: "active",
    }));

    const { error } = await sb.from("global_opportunities").insert(rows);
    if (error) throw error;

    return new Response(JSON.stringify({ message: `Seeded ${rows.length} global opportunities` }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (err) {
    return new Response(JSON.stringify({ error: (err as Error).message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
