
INSERT INTO companies (name, domain, sector, sub_sector, hq_country, hq_city, founded_year, employee_count, stage, description, market_type) VALUES
('Nuclera Therapeutics', 'nuclera.com', 'Biotech', 'Gene Therapy', 'US', 'Cambridge', 2019, 85, 'Series B', 'Next-generation gene therapy platform using lipid nanoparticle delivery for rare diseases.', 'private'),
('OmniGenome', 'omnigenome.ai', 'Biotech', 'Genomics', 'US', 'San Diego', 2020, 120, 'Series A', 'AI-driven genomics platform for precision oncology and drug target discovery.', 'private'),
('BioVault Sciences', 'biovault.bio', 'Biotech', 'Biobanking', 'GB', 'London', 2018, 200, 'Series C', 'Automated cryogenic biobanking infrastructure for pharmaceutical research.', 'private'),
('CellForge Bio', 'cellforge.com', 'Biotech', 'Cell Therapy', 'US', 'Philadelphia', 2021, 60, 'Series A', 'Scalable allogeneic cell therapy manufacturing platform.', 'private'),
('Proteon Dynamics', 'proteondynamics.com', 'Biotech', 'Protein Engineering', 'CH', 'Basel', 2019, 95, 'Series B', 'Computational protein design for novel therapeutic antibodies.', 'private'),
('SynaptoRx', 'synaptorx.com', 'Biotech', 'Neuroscience', 'US', 'Boston', 2020, 75, 'Series A', 'Small molecule therapeutics targeting synaptic dysfunction in neurodegeneration.', 'private'),
('MicrobiomX', 'microbiomx.com', 'Biotech', 'Microbiome', 'NL', 'Amsterdam', 2018, 110, 'Series B', 'Engineered live biotherapeutics for inflammatory bowel disease.', 'private'),
('Epigenia Labs', 'epigenialabs.com', 'Biotech', 'Epigenetics', 'US', 'San Francisco', 2021, 45, 'Seed', 'Epigenetic editing platform for age-related disease reversal.', 'private'),
('PhageWorks', 'phageworks.bio', 'Biotech', 'Antimicrobials', 'GB', 'Edinburgh', 2019, 80, 'Series A', 'Phage therapy development for antibiotic-resistant infections.', 'private'),
('NeuroPath AI', 'neuropathai.com', 'Biotech', 'Digital Pathology', 'DE', 'Munich', 2020, 65, 'Series A', 'AI-powered neuropathology diagnostics for neurodegenerative diseases.', 'private'),
('RiboTech Sciences', 'ribotechsci.com', 'Biotech', 'RNA Therapeutics', 'US', 'Cambridge', 2019, 150, 'Series C', 'Next-gen mRNA platform with self-amplifying RNA technology.', 'private'),
('Verdant Biosciences', 'verdantbio.com', 'Biotech', 'Agricultural Biology', 'US', 'Research Triangle', 2017, 180, 'Growth', 'Biological crop protection and enhancement solutions.', 'private'),
('Quantum Biogenics', 'quantumbio.com', 'Biotech', 'Quantum Biology', 'US', 'Palo Alto', 2022, 30, 'Seed', 'Quantum computing applications for drug molecular simulation.', 'private'),
('GeneStar Therapeutics', 'genestar.io', 'Biotech', 'Gene Therapy', 'JP', 'Tokyo', 2020, 90, 'Series B', 'In vivo gene editing platform for liver metabolic disorders.', 'private'),
('NovaBiome', 'novabiome.com', 'Biotech', 'Synthetic Biology', 'US', 'Boston', 2019, 130, 'Series B', 'Synthetic biology platform for sustainable chemical production.', 'private'),
('ImmunoPrecision', 'immunoprecision.bio', 'Biotech', 'Immunology', 'CA', 'Vancouver', 2018, 95, 'Series B', 'Precision immunology therapeutics for autoimmune conditions.', 'private'),
('CryoVita', 'cryovita.com', 'Biotech', 'Cryopreservation', 'SE', 'Stockholm', 2021, 40, 'Seed', 'Advanced organ cryopreservation technology for transplant medicine.', 'private'),
('BioSentinel Dx', 'biosentinel.io', 'Biotech', 'Diagnostics', 'US', 'Austin', 2020, 70, 'Series A', 'Multiplexed liquid biopsy diagnostics for early cancer detection.', 'private'),
('StemCore Bio', 'stemcore.bio', 'Biotech', 'Stem Cells', 'KR', 'Seoul', 2019, 110, 'Series B', 'iPSC-derived cell therapies for cardiac regeneration.', 'private'),
('OxBridge Pharma', 'oxbridgepharma.com', 'Biotech', 'Drug Delivery', 'GB', 'Oxford', 2018, 85, 'Series B', 'Targeted nanoparticle drug delivery for solid tumors.', 'private'),
('Helix Bioinformatics', 'helixbioinfo.com', 'Biotech', 'Bioinformatics', 'IL', 'Tel Aviv', 2020, 55, 'Series A', 'Cloud-native bioinformatics platform for clinical genomics.', 'private'),
('MetaVax', 'metavax.bio', 'Biotech', 'Vaccines', 'US', 'Baltimore', 2021, 65, 'Series A', 'Metagenomic vaccine discovery platform for emerging pathogens.', 'private'),
('ChromaDx', 'chromadx.com', 'Biotech', 'Diagnostics', 'SG', 'Singapore', 2019, 100, 'Series B', 'Point-of-care chromatographic diagnostics for tropical diseases.', 'private'),
('BioFlux Therapeutics', 'bioflux.com', 'Biotech', 'Metabolic', 'US', 'San Francisco', 2020, 80, 'Series A', 'Novel metabolic pathway modulators for obesity and NASH.', 'private'),
('AntaGen', 'antagen.com', 'Biotech', 'Anti-Aging', 'US', 'La Jolla', 2022, 35, 'Seed', 'Senolytic therapies targeting cellular aging mechanisms.', 'private'),
('CropMind', 'cropmind.ai', 'AgTech', 'Precision Agriculture', 'US', 'Des Moines', 2019, 95, 'Series B', 'AI-driven crop management platform using satellite and drone imagery.', 'private'),
('AquaFarm Technologies', 'aquafarmtech.com', 'AgTech', 'Aquaculture', 'NO', 'Bergen', 2018, 120, 'Series B', 'Automated aquaculture management systems for sustainable fish farming.', 'private'),
('SoilSense', 'soilsense.io', 'AgTech', 'Soil Health', 'NL', 'Wageningen', 2020, 45, 'Series A', 'IoT soil monitoring and regenerative agriculture analytics.', 'private'),
('VertiFresh', 'vertifresh.com', 'AgTech', 'Vertical Farming', 'AE', 'Dubai', 2019, 200, 'Series C', 'Climate-controlled vertical farming for leafy greens in arid regions.', 'private'),
('PolliTech', 'pollitech.com', 'AgTech', 'Pollination', 'AU', 'Melbourne', 2021, 30, 'Seed', 'Robotic pollination drones for commercial orchards.', 'private'),
('GrainChain', 'grainchain.io', 'AgTech', 'Supply Chain', 'US', 'Houston', 2018, 110, 'Series B', 'Blockchain-based grain supply chain and commodity trading platform.', 'private'),
('FertiSmart', 'fertismart.com', 'AgTech', 'Fertilizer Tech', 'BR', 'Sao Paulo', 2019, 75, 'Series A', 'Precision fertilizer application using variable rate technology.', 'private'),
('LivestockIQ', 'livestockiq.com', 'AgTech', 'Animal Health', 'GB', 'Cambridge', 2020, 60, 'Series A', 'Wearable health monitoring for dairy and beef cattle.', 'private'),
('BioHarvest', 'bioharvest.ag', 'AgTech', 'Cellular Agriculture', 'IL', 'Rehovot', 2018, 85, 'Series B', 'Plant cell cultivation for nutraceutical and food ingredient production.', 'private'),
('AgriDrone Systems', 'agridrone.com', 'AgTech', 'Drone Services', 'US', 'Fargo', 2019, 55, 'Series A', 'Autonomous drone spraying and crop scouting services.', 'private'),
('InsectaPro', 'insectapro.com', 'AgTech', 'Alternative Protein', 'FI', 'Helsinki', 2020, 90, 'Series A', 'Insect protein production for animal feed and pet food.', 'private'),
('PhytoGen Crop Science', 'phytogencrop.com', 'AgTech', 'Seed Technology', 'US', 'St. Louis', 2017, 140, 'Series C', 'Non-GMO seed trait development for drought resistance.', 'private'),
('AgroStar Platform', 'agrostar.ag', 'AgTech', 'Marketplace', 'IN', 'Pune', 2018, 250, 'Series C', 'B2B agricultural inputs marketplace connecting farmers to suppliers.', 'private'),
('HydroNova', 'hydronova.io', 'AgTech', 'Hydroponics', 'NL', 'Rotterdam', 2021, 40, 'Seed', 'Modular hydroponic systems for urban commercial growing.', 'private'),
('FarmBot AI', 'farmbot-ai.com', 'AgTech', 'Robotics', 'US', 'Davis', 2020, 50, 'Series A', 'Autonomous weeding and harvesting robots for row crops.', 'private'),
('SolarVault Energy', 'solarvault.com', 'CleanTech', 'Energy Storage', 'US', 'Denver', 2019, 180, 'Series C', 'Long-duration iron-air battery storage for grid-scale applications.', 'private'),
('CarbonCapture Inc', 'carboncapture.com', 'CleanTech', 'Carbon Removal', 'US', 'Los Angeles', 2018, 150, 'Series B', 'Direct air capture modules using solid sorbent technology.', 'private'),
('HydroPure Tech', 'hydropure.com', 'CleanTech', 'Water Treatment', 'IL', 'Haifa', 2019, 90, 'Series B', 'Electrochemical water treatment for industrial wastewater.', 'private'),
('WindForge Energy', 'windforge.com', 'CleanTech', 'Wind Energy', 'DK', 'Copenhagen', 2018, 200, 'Growth', 'Floating offshore wind turbine technology for deep water deployment.', 'private'),
('GreenH2 Systems', 'greenh2.com', 'CleanTech', 'Green Hydrogen', 'DE', 'Hamburg', 2020, 120, 'Series B', 'PEM electrolyzer manufacturing for green hydrogen production.', 'private'),
('CircularChem', 'circularchem.com', 'CleanTech', 'Chemical Recycling', 'NL', 'Eindhoven', 2019, 95, 'Series B', 'Chemical recycling of mixed plastic waste into virgin-grade feedstock.', 'private'),
('ThermalEdge', 'thermaledge.com', 'CleanTech', 'Geothermal', 'US', 'Houston', 2020, 75, 'Series A', 'Enhanced geothermal systems using drilling technology from oil and gas.', 'private'),
('EcoGrid Solutions', 'ecogrid.io', 'CleanTech', 'Smart Grid', 'SE', 'Stockholm', 2018, 110, 'Series B', 'AI-powered grid management for distributed renewable energy.', 'private'),
('BioCement Co', 'biocement.co', 'CleanTech', 'Green Building', 'US', 'San Francisco', 2021, 45, 'Series A', 'Biologically-grown cement using microorganisms reducing CO2 by 90 percent.', 'private'),
('NuclearMicro', 'nuclearmicro.com', 'CleanTech', 'Nuclear', 'US', 'Seattle', 2019, 160, 'Series C', 'Microreactor nuclear power plants for remote communities and data centers.', 'private'),
('OceanPower Systems', 'oceanpower.com', 'CleanTech', 'Marine Energy', 'GB', 'Edinburgh', 2017, 80, 'Series B', 'Wave energy converters for coastal power generation.', 'private'),
('VoltStack', 'voltstack.io', 'CleanTech', 'EV Infrastructure', 'US', 'Austin', 2020, 130, 'Series B', 'Ultra-fast EV charging network with integrated battery storage.', 'private'),
('AgriSolar', 'agrisolar.com', 'CleanTech', 'Agrivoltaics', 'FR', 'Lyon', 2019, 70, 'Series A', 'Dual-use solar installations for simultaneous farming and power generation.', 'private'),
('MethaneSense', 'methanesense.com', 'CleanTech', 'Emissions Monitoring', 'CA', 'Calgary', 2020, 55, 'Series A', 'Satellite-based methane leak detection for oil and gas operations.', 'private'),
('FlowBattery Corp', 'flowbattery.com', 'CleanTech', 'Energy Storage', 'AU', 'Sydney', 2018, 100, 'Series B', 'Vanadium redox flow batteries for commercial and industrial storage.', 'private'),
('SustainPack', 'sustainpack.com', 'CleanTech', 'Sustainable Packaging', 'FI', 'Espoo', 2019, 85, 'Series A', 'Molded fiber packaging to replace single-use plastics.', 'private'),
('CleanAir Tech', 'cleanairtech.com', 'CleanTech', 'Air Quality', 'IN', 'Bangalore', 2020, 65, 'Series A', 'Industrial air filtration systems for particulate and VOC removal.', 'private'),
('HeatPump Pro', 'heatpumppro.com', 'CleanTech', 'HVAC', 'US', 'Portland', 2019, 90, 'Series B', 'High-efficiency industrial heat pumps for process heating decarbonization.', 'private'),
('TidalGen', 'tidalgen.com', 'CleanTech', 'Tidal Energy', 'GB', 'Bristol', 2018, 60, 'Series A', 'Modular tidal stream turbines for predictable marine energy.', 'private'),
('PyroChar', 'pyrochar.com', 'CleanTech', 'Biochar', 'US', 'Bend', 2021, 35, 'Seed', 'Pyrolysis biochar production for carbon sequestration and soil enhancement.', 'private'),
('MedSync Health', 'medsync.health', 'Digital Health', 'Care Coordination', 'US', 'Nashville', 2019, 150, 'Series B', 'Interoperable care coordination platform for multi-provider patient management.', 'private'),
('NeuroWell', 'neurowell.io', 'Digital Health', 'Mental Health', 'US', 'San Francisco', 2020, 80, 'Series A', 'Digital therapeutics platform for anxiety and depression using CBT protocols.', 'private'),
('PharmaTrace', 'pharmatrace.com', 'Digital Health', 'Supply Chain', 'CH', 'Zurich', 2018, 95, 'Series B', 'Blockchain pharmaceutical supply chain verification and anti-counterfeiting.', 'private'),
('RemoteICU', 'remoteicu.com', 'Digital Health', 'Telehealth', 'US', 'Houston', 2019, 120, 'Series B', 'Tele-ICU platform enabling remote critical care monitoring by intensivists.', 'private'),
('DermaAI', 'dermaai.com', 'Digital Health', 'Dermatology', 'GB', 'London', 2020, 55, 'Series A', 'AI dermatology screening app with 95 percent diagnostic accuracy for skin conditions.', 'private'),
('CardioPulse', 'cardiopulse.io', 'Digital Health', 'Cardiology', 'IL', 'Herzliya', 2019, 70, 'Series A', 'Wearable continuous cardiac monitoring with AI arrhythmia detection.', 'private'),
('TherapyBot', 'therapybot.ai', 'Digital Health', 'Mental Health', 'US', 'New York', 2021, 40, 'Seed', 'AI therapy companion for between-session mental health support.', 'private'),
('OncologyCloud', 'oncologycloud.com', 'Digital Health', 'Oncology', 'US', 'Cambridge', 2018, 180, 'Series C', 'Cloud-based oncology decision support and clinical trial matching.', 'private'),
('SleepWise', 'sleepwise.health', 'Digital Health', 'Sleep', 'DE', 'Berlin', 2020, 45, 'Series A', 'Digital sleep therapy platform combining CBT-I with wearable data.', 'private'),
('PhysioTrack', 'physiotrack.io', 'Digital Health', 'Physical Therapy', 'AU', 'Sydney', 2019, 60, 'Series A', 'Computer vision-based physical therapy exercise tracking and compliance.', 'private'),
('MedLedger', 'medledger.io', 'Digital Health', 'Health Records', 'US', 'Chicago', 2020, 85, 'Series B', 'Patient-controlled health record platform with HIPAA-compliant sharing.', 'private'),
('PediatricAI', 'pediatricai.com', 'Digital Health', 'Pediatrics', 'US', 'Boston', 2021, 35, 'Seed', 'AI pediatric triage and symptom checker for parents and primary care.', 'private'),
('VisionScreen', 'visionscreen.ai', 'Digital Health', 'Ophthalmology', 'SG', 'Singapore', 2019, 50, 'Series A', 'Smartphone-based vision screening and diabetic retinopathy detection.', 'private'),
('RehabFlow', 'rehabflow.com', 'Digital Health', 'Rehabilitation', 'CA', 'Toronto', 2020, 55, 'Series A', 'Post-surgical rehabilitation tracking and outcome measurement platform.', 'private'),
('GeriCare Tech', 'gericaretech.com', 'Digital Health', 'Elderly Care', 'JP', 'Tokyo', 2018, 110, 'Series B', 'IoT-enabled elderly monitoring and fall prevention system.', 'private'),
('NutritionIQ', 'nutritioniq.health', 'Digital Health', 'Nutrition', 'US', 'Los Angeles', 2021, 40, 'Seed', 'Personalized nutrition planning using microbiome and genetic data.', 'private'),
('LabFlow Systems', 'labflow.io', 'Digital Health', 'Lab Management', 'US', 'San Jose', 2019, 75, 'Series A', 'Clinical laboratory workflow automation and LIMS platform.', 'private'),
('FertilityPath', 'fertilitypath.com', 'Digital Health', 'Fertility', 'US', 'New York', 2020, 65, 'Series A', 'Fertility treatment optimization using AI outcome prediction models.', 'private'),
('RespiWatch', 'respirwatch.com', 'Digital Health', 'Respiratory', 'GB', 'Manchester', 2019, 50, 'Series A', 'Wearable respiratory monitoring for COPD and asthma management.', 'private'),
('HealthEquity AI', 'healthequityai.com', 'Digital Health', 'Health Equity', 'US', 'Atlanta', 2021, 30, 'Seed', 'AI platform to identify and address healthcare disparities in underserved communities.', 'private'),
('CulturedFoods Co', 'culturedfoods.com', 'FoodTech', 'Cultivated Meat', 'US', 'San Francisco', 2019, 120, 'Series B', 'Cultivated beef and poultry production using bioreactor technology.', 'private'),
('FermentIQ', 'fermentiq.com', 'FoodTech', 'Precision Fermentation', 'IL', 'Tel Aviv', 2020, 80, 'Series A', 'Precision fermentation for dairy-identical whey and casein proteins.', 'private'),
('NutriPrint', 'nutriprint.io', 'FoodTech', '3D Food Printing', 'NL', 'Amsterdam', 2021, 35, 'Seed', '3D food printing technology for personalized nutrition delivery.', 'private'),
('SmartKitchen OS', 'smartkitchenos.com', 'FoodTech', 'Kitchen Tech', 'US', 'Seattle', 2019, 90, 'Series B', 'Connected kitchen platform for commercial food service operations.', 'private'),
('MycoProtein Labs', 'mycoprotein.com', 'FoodTech', 'Alternative Protein', 'DK', 'Copenhagen', 2020, 55, 'Series A', 'Mycelium-based meat alternatives with whole-cut texture fidelity.', 'private'),
('FreshRoute', 'freshroute.com', 'FoodTech', 'Cold Chain', 'US', 'Dallas', 2018, 150, 'Series C', 'IoT cold chain monitoring and predictive shelf-life analytics.', 'private'),
('PlantPure Foods', 'plantpure.com', 'FoodTech', 'Plant-Based', 'US', 'Los Angeles', 2019, 100, 'Series B', 'Whole-food plant-based meal delivery for healthcare institutions.', 'private'),
('AlgaeNutrition', 'algaenutrition.com', 'FoodTech', 'Algae', 'AU', 'Perth', 2020, 45, 'Series A', 'Microalgae cultivation for omega-3 rich food ingredients.', 'private'),
('WasteNot AI', 'wastenot.ai', 'FoodTech', 'Food Waste', 'GB', 'London', 2019, 60, 'Series A', 'AI-powered food waste reduction platform for grocery and foodservice.', 'private'),
('BrewTech Systems', 'brewtech.io', 'FoodTech', 'Beverage', 'US', 'Portland', 2020, 40, 'Seed', 'Automated craft beverage production and quality control systems.', 'private'),
-- MarTech, ConstructionTech, HRTech, Quantum Computing, Media
('AdNexus', 'adnexus.ai', 'MarTech', 'Advertising', 'US', 'New York', 2019, 110, 'Series B', 'AI-powered contextual advertising platform for cookieless targeting.', 'private'),
('BuildOS', 'buildos.io', 'ConstructionTech', 'Project Management', 'US', 'Chicago', 2018, 140, 'Series B', 'Construction project management platform with BIM integration.', 'private'),
('TalentGraph', 'talentgraph.com', 'HRTech', 'Talent Analytics', 'US', 'San Francisco', 2020, 75, 'Series A', 'Graph-based talent mapping and organizational network analytics.', 'private'),
('QubitSoft', 'qubitsoft.com', 'Quantum Computing', 'Software', 'US', 'Boulder', 2019, 60, 'Series A', 'Quantum algorithm development toolkit for enterprise optimization.', 'private'),
('StreamVault Media', 'streamvault.com', 'Media/Entertainment', 'Streaming', 'US', 'Los Angeles', 2020, 95, 'Series B', 'Creator-first streaming platform with integrated monetization tools.', 'private'),
('PredictiveHR', 'predictivehr.com', 'HRTech', 'Workforce Planning', 'GB', 'London', 2019, 85, 'Series A', 'AI-driven workforce planning and attrition risk prediction.', 'private'),
('SiteVision 3D', 'sitevision3d.com', 'ConstructionTech', 'Surveying', 'SE', 'Gothenburg', 2018, 65, 'Series A', 'Mixed reality surveying and site planning for construction.', 'private'),
('ContentForge', 'contentforge.ai', 'MarTech', 'Content Creation', 'US', 'Austin', 2021, 50, 'Seed', 'AI content generation platform optimized for B2B marketing teams.', 'private'),
('IonQ Applied', 'ionqapplied.com', 'Quantum Computing', 'Applications', 'US', 'College Park', 2020, 45, 'Series A', 'Quantum computing as a service for financial modeling and drug discovery.', 'private'),
('PodNetwork', 'podnetwork.fm', 'Media/Entertainment', 'Podcasting', 'US', 'Brooklyn', 2019, 40, 'Seed', 'B2B podcast network and audience analytics for enterprise brands.', 'private'),
('RoboSite', 'robosite.ai', 'ConstructionTech', 'Robotics', 'JP', 'Osaka', 2019, 100, 'Series B', 'Autonomous construction robots for concrete pouring and bricklaying.', 'private'),
('SkillPulse', 'skillpulse.io', 'HRTech', 'Learning', 'DE', 'Berlin', 2020, 70, 'Series A', 'Skills-based learning platform with adaptive curriculum for enterprises.', 'private'),
('DataPixel', 'datapixel.ai', 'MarTech', 'Analytics', 'US', 'San Francisco', 2019, 80, 'Series B', 'Privacy-first marketing attribution and customer journey analytics.', 'private'),
('GameForge Studios', 'gameforge.dev', 'Media/Entertainment', 'Gaming', 'FI', 'Helsinki', 2018, 130, 'Series B', 'Cloud-native game development platform with real-time multiplayer infrastructure.', 'private'),
('QuantumSafe', 'quantumsafe.io', 'Quantum Computing', 'Security', 'CH', 'Geneva', 2020, 55, 'Series A', 'Post-quantum cryptography solutions for enterprise data protection.', 'private'),
('ModularBuild', 'modularbuild.co', 'ConstructionTech', 'Modular', 'US', 'Nashville', 2019, 180, 'Series C', 'Off-site modular construction for multi-family and hospitality projects.', 'private'),
('PayrollStack', 'payrollstack.com', 'HRTech', 'Payroll', 'US', 'Miami', 2020, 65, 'Series A', 'Global payroll and compliance platform for distributed teams.', 'private'),
('StudioAI', 'studioai.com', 'Media/Entertainment', 'Production', 'US', 'Los Angeles', 2021, 45, 'Seed', 'AI-powered film pre-production planning and virtual production tools.', 'private'),
('EngagePlatform', 'engageplatform.com', 'MarTech', 'Customer Engagement', 'US', 'Boston', 2018, 120, 'Series C', 'Omnichannel customer engagement orchestration for enterprise.', 'private'),
('QuantumEdge', 'quantumedge.tech', 'Quantum Computing', 'Hardware', 'US', 'San Jose', 2019, 85, 'Series B', 'Superconducting qubit processors optimized for error correction.', 'private'),
('SafetyNet Construction', 'safetynetconstruction.com', 'ConstructionTech', 'Safety', 'AU', 'Sydney', 2020, 50, 'Series A', 'IoT wearable safety monitoring for construction workers.', 'private'),
('CultureAmp Pro', 'cultureamppro.com', 'HRTech', 'Employee Experience', 'AU', 'Melbourne', 2019, 95, 'Series B', 'Employee engagement analytics and action planning platform.', 'private'),
('MusicMint', 'musicmint.io', 'Media/Entertainment', 'Music', 'GB', 'London', 2021, 30, 'Seed', 'Blockchain-based music rights management and royalty distribution.', 'private'),
('ConcreteAI', 'concreteai.com', 'ConstructionTech', 'Materials', 'US', 'Pittsburgh', 2020, 40, 'Seed', 'AI-optimized concrete mix design reducing cement use by 40 percent.', 'private'),
('RecruitFlow', 'recruitflow.io', 'HRTech', 'Recruiting', 'US', 'Denver', 2019, 90, 'Series B', 'AI recruiting platform with bias-reduction and structured interviewing.', 'private'),
-- Additional SaaS/Enterprise
('DataWeave Pro', 'dataweavepro.com', 'Enterprise SaaS', 'Data Integration', 'US', 'San Francisco', 2018, 200, 'Series C', 'No-code data integration and transformation platform for enterprise.', 'private'),
('CloudGuard Security', 'cloudguard.io', 'Cybersecurity', 'Cloud Security', 'US', 'San Jose', 2019, 150, 'Series B', 'Cloud-native application protection platform with runtime security.', 'private'),
('SupplyChainOS', 'supplychainos.com', 'Enterprise SaaS', 'Supply Chain', 'US', 'Atlanta', 2018, 180, 'Series C', 'End-to-end supply chain visibility and optimization platform.', 'private'),
('LegalTech AI', 'legaltechai.com', 'LegalTech', 'Contract Management', 'US', 'New York', 2019, 95, 'Series B', 'AI-powered contract analysis and lifecycle management.', 'private'),
('InsurTech Connect', 'insurtechconnect.com', 'InsurTech', 'Distribution', 'US', 'Chicago', 2020, 110, 'Series B', 'Embedded insurance API platform for digital commerce.', 'private'),
('PropTech Analytics', 'proptechanalytics.com', 'PropTech', 'Analytics', 'GB', 'London', 2019, 70, 'Series A', 'Commercial real estate portfolio analytics and benchmarking.', 'private'),
('EdTech Learning', 'edtechlearning.com', 'EdTech', 'K-12', 'US', 'Boston', 2018, 160, 'Series C', 'Adaptive learning platform for K-12 math and science education.', 'private'),
('FinOps Platform', 'finopsplatform.com', 'FinTech', 'Cloud FinOps', 'US', 'Seattle', 2020, 80, 'Series A', 'Cloud cost management and optimization for multi-cloud enterprises.', 'private'),
('DevSecOps Inc', 'devsecops.io', 'Cybersecurity', 'AppSec', 'IL', 'Tel Aviv', 2019, 120, 'Series B', 'Developer-first application security testing and remediation.', 'private'),
('RevOps Engine', 'revopsengine.com', 'Enterprise SaaS', 'Revenue Operations', 'US', 'San Francisco', 2020, 65, 'Series A', 'Unified revenue operations platform connecting sales, marketing, and CS.', 'private'),
('SpaceTech Orbital', 'spacetechorbital.com', 'SpaceTech', 'Satellites', 'US', 'Hawthorne', 2019, 200, 'Series C', 'Small satellite manufacturing and earth observation data services.', 'private'),
('ClimateRisk Analytics', 'climaterisk.ai', 'CleanTech', 'Risk Analytics', 'US', 'New York', 2020, 55, 'Series A', 'Climate risk modeling and scenario analysis for institutional investors.', 'private'),
('TravelOS', 'travelossystem.com', 'Travel Tech', 'B2B Platform', 'US', 'Miami', 2019, 90, 'Series B', 'Travel management platform for corporate and group travel.', 'private'),
('WealthFront Pro', 'wealthfrontpro.com', 'FinTech', 'Wealth Management', 'US', 'Palo Alto', 2018, 130, 'Growth', 'Digital wealth management platform for RIAs and family offices.', 'private'),
('LogiTech Fleet', 'logitechfleet.com', 'Logistics', 'Fleet Management', 'US', 'Dallas', 2019, 100, 'Series B', 'AI fleet management and route optimization for last-mile delivery.', 'private'),
('CyberVault', 'cybervault.io', 'Cybersecurity', 'Data Protection', 'US', 'Washington DC', 2020, 75, 'Series A', 'Zero-trust data protection platform for government and enterprise.', 'private'),
('SmartFactory AI', 'smartfactory.ai', 'Manufacturing', 'Industry 4.0', 'DE', 'Stuttgart', 2019, 110, 'Series B', 'AI-driven predictive maintenance and quality control for manufacturing.', 'private'),
('GovTech Solutions', 'govtechsolutions.com', 'GovTech', 'Digital Services', 'US', 'Washington DC', 2018, 150, 'Series C', 'Digital transformation platform for state and local government.', 'private'),
('AutoDrive Systems', 'autodrivesystems.com', 'Automotive', 'Autonomous Vehicles', 'US', 'Pittsburgh', 2019, 250, 'Series C', 'Level 4 autonomous driving technology for commercial trucks.', 'private'),
('BioProcess Tech', 'bioprocesstech.com', 'Biotech', 'Manufacturing', 'US', 'Durham', 2020, 85, 'Series A', 'Continuous bioprocessing equipment for biopharmaceutical manufacturing.', 'private');
