
-- BATCH 2: More companies (FinTech, Enterprise, International diversity) + Distressed Assets
INSERT INTO companies (name, domain, sector, sub_sector, hq_country, hq_city, founded_year, employee_count, stage, description, market_type) VALUES
('NeoBank Asia', 'neobankasia.com', 'FinTech', 'Digital Banking', 'SG', 'Singapore', 2019, 200, 'Series C', 'Digital-first banking platform for SMEs across Southeast Asia.', 'private'),
('PayStream Global', 'paystreamglobal.com', 'FinTech', 'Payments', 'GB', 'London', 2018, 180, 'Growth', 'Cross-border B2B payments infrastructure for emerging markets.', 'private'),
('CreditPulse', 'creditpulse.ai', 'FinTech', 'Credit', 'US', 'Charlotte', 2020, 90, 'Series B', 'AI credit underwriting for thin-file borrowers using alternative data.', 'private'),
('BlockSettle', 'blocksettle.com', 'FinTech', 'Digital Assets', 'CH', 'Zug', 2019, 65, 'Series A', 'Institutional-grade digital asset custody and trading infrastructure.', 'private'),
('MicroLend', 'microlend.io', 'FinTech', 'Lending', 'KE', 'Nairobi', 2018, 130, 'Series B', 'Mobile-first micro-lending platform for African SMEs.', 'private'),
('TradeSynth', 'tradesynth.com', 'FinTech', 'Trading', 'US', 'New York', 2020, 75, 'Series A', 'Synthetic trading products for retail investors with fractional access.', 'private'),
('ComplianceHub', 'compliancehub.io', 'FinTech', 'RegTech', 'US', 'Washington DC', 2019, 100, 'Series B', 'Automated regulatory compliance monitoring for financial institutions.', 'private'),
('EmbedFinance', 'embedfinance.com', 'FinTech', 'Embedded Finance', 'DE', 'Berlin', 2020, 85, 'Series A', 'Banking-as-a-service API for embedding financial products.', 'private'),
('TaxFlow Pro', 'taxflowpro.com', 'FinTech', 'Tax', 'US', 'San Francisco', 2019, 60, 'Series A', 'Automated tax optimization for small business owners and freelancers.', 'private'),
('InvestorHub', 'investorhub.io', 'FinTech', 'Investor Relations', 'AU', 'Sydney', 2018, 70, 'Series A', 'Digital investor relations platform for private companies and funds.', 'private'),
-- More international companies
('Sakura Robotics', 'sakurarobotics.jp', 'Robotics', 'Industrial', 'JP', 'Nagoya', 2018, 150, 'Series C', 'Collaborative industrial robots for precision electronics assembly.', 'private'),
('Nordic Clean Energy', 'nordicclean.com', 'CleanTech', 'Renewable', 'NO', 'Oslo', 2019, 95, 'Series B', 'Integrated renewable energy solutions for Nordic industrial facilities.', 'private'),
('Zurich InsurTech', 'zurichinsurtech.ch', 'InsurTech', 'Commercial', 'CH', 'Zurich', 2020, 80, 'Series A', 'Parametric insurance products for climate-related commercial risks.', 'private'),
('Seoul AI Labs', 'seoulailabs.kr', 'AI/ML', 'Computer Vision', 'KR', 'Seoul', 2019, 120, 'Series B', 'Computer vision platform for manufacturing quality inspection.', 'private'),
('Dubai PropTech', 'dubaiproptech.ae', 'PropTech', 'Marketplace', 'AE', 'Dubai', 2018, 100, 'Series B', 'Fractional real estate investment platform for Gulf region properties.', 'private'),
('Bengaluru SaaS', 'bengalurusaas.in', 'Enterprise SaaS', 'CRM', 'IN', 'Bangalore', 2019, 200, 'Series C', 'AI-powered CRM platform designed for Indian enterprise sales teams.', 'private'),
('Sao Paulo FinTech', 'spfintech.com.br', 'FinTech', 'Banking', 'BR', 'Sao Paulo', 2018, 250, 'Growth', 'Digital banking for Brazilian micro-enterprises and gig workers.', 'private'),
('Mexico City Logistics', 'mxcitylogistics.com', 'Logistics', 'Last Mile', 'MX', 'Mexico City', 2019, 180, 'Series C', 'Tech-enabled last-mile delivery network for Mexican e-commerce.', 'private'),
('Bogota HealthTech', 'bogotahealthtech.co', 'Digital Health', 'Telemedicine', 'CO', 'Bogota', 2020, 70, 'Series A', 'Telemedicine platform connecting rural communities to urban specialists.', 'private'),
('Riyadh EdTech', 'riyadhedtech.sa', 'EdTech', 'Corporate Training', 'SA', 'Riyadh', 2020, 60, 'Series A', 'Arabic-first corporate learning platform for Saudi Vision 2030 skills.', 'private'),
('Helsinki Gaming', 'helsinkigaming.fi', 'Media/Entertainment', 'Mobile Gaming', 'FI', 'Helsinki', 2019, 85, 'Series B', 'Mobile-first casual gaming studio with 50M monthly active players.', 'private'),
('Copenhagen BioTech', 'cpnbiotech.dk', 'Biotech', 'Industrial Biology', 'DK', 'Copenhagen', 2018, 110, 'Series B', 'Enzyme engineering for sustainable industrial processes.', 'private'),
('Amsterdam LegalTech', 'amlegaltech.nl', 'LegalTech', 'Compliance', 'NL', 'Amsterdam', 2020, 55, 'Series A', 'GDPR and privacy compliance automation for European enterprises.', 'private'),
('Sydney ClimateTech', 'sydneyclimate.au', 'CleanTech', 'Carbon Markets', 'AU', 'Sydney', 2019, 70, 'Series A', 'Carbon credit marketplace and verification platform for APAC.', 'private'),
('Lagos Payments', 'lagospayments.ng', 'FinTech', 'Payments', 'NG', 'Lagos', 2018, 150, 'Series B', 'Pan-African payment processing infrastructure for cross-border commerce.', 'private'),
('Taipei Semiconductor', 'taipeisc.tw', 'Hardware', 'Semiconductors', 'TW', 'Taipei', 2017, 300, 'Growth', 'Advanced chiplet packaging technology for high-performance computing.', 'private'),
('Vienna DeepTech', 'viennadeeptech.at', 'AI/ML', 'Deep Learning', 'AT', 'Vienna', 2020, 45, 'Seed', 'Neuromorphic computing chips for edge AI applications.', 'private'),
('Warsaw CyberSec', 'warsawcybersec.pl', 'Cybersecurity', 'Threat Intel', 'PL', 'Warsaw', 2019, 80, 'Series A', 'Dark web threat intelligence and brand protection monitoring.', 'private'),
('Lisbon Marketplace', 'lisbonmp.pt', 'Enterprise SaaS', 'Marketplace', 'PT', 'Lisbon', 2020, 50, 'Seed', 'B2B marketplace platform for Portuguese artisan food producers.', 'private'),
('Cape Town AgTech', 'capetownag.za', 'AgTech', 'Water Tech', 'ZA', 'Cape Town', 2019, 60, 'Series A', 'Smart irrigation systems for water-scarce African agriculture.', 'private'),
-- More US companies across sectors
('Forge Materials', 'forgematerials.com', 'Manufacturing', 'Advanced Materials', 'US', 'Cleveland', 2018, 120, 'Series B', 'Advanced composite materials for aerospace and defense applications.', 'private'),
('TruckPark', 'truckpark.io', 'Logistics', 'Trucking', 'US', 'Nashville', 2019, 65, 'Series A', 'Smart truck parking reservation and yard management platform.', 'private'),
('PetHealth AI', 'pethealthai.com', 'Digital Health', 'Veterinary', 'US', 'Denver', 2020, 55, 'Series A', 'AI diagnostics platform for veterinary practices and pet owners.', 'private'),
('EnergyOS', 'energyos.io', 'CleanTech', 'Energy Management', 'US', 'Chicago', 2019, 100, 'Series B', 'Building energy optimization platform for commercial real estate.', 'private'),
('SecureID Cloud', 'secureidcloud.com', 'Cybersecurity', 'Identity', 'US', 'San Jose', 2018, 140, 'Series C', 'Decentralized identity verification for financial services.', 'private'),
('FarmCredit', 'farmcredit.ai', 'AgTech', 'Agricultural Finance', 'US', 'Omaha', 2020, 45, 'Series A', 'AI-powered agricultural lending and crop insurance underwriting.', 'private'),
('RetailOS', 'retailos.com', 'Enterprise SaaS', 'Retail Tech', 'US', 'Minneapolis', 2019, 110, 'Series B', 'Unified commerce platform for mid-market retailers.', 'private'),
('DroneDelivery Co', 'dronedelivery.co', 'Logistics', 'Drones', 'US', 'Bentonville', 2020, 80, 'Series A', 'FAA-approved drone delivery service for rural and suburban markets.', 'private'),
('NeuraMed', 'neuramed.io', 'Biotech', 'Neurostimulation', 'US', 'Minneapolis', 2019, 95, 'Series B', 'Non-invasive neurostimulation devices for chronic pain management.', 'private'),
('UrbanMobility', 'urbanmobility.com', 'Transportation', 'Micro-mobility', 'US', 'Portland', 2018, 130, 'Series C', 'Integrated micro-mobility platform combining e-bikes and e-scooters.', 'private');

-- BATCH 2B: Distressed Assets (230 new)
INSERT INTO distressed_assets (name, asset_type, distress_type, sector, description, estimated_value, asking_price, discount_pct, location_city, location_state, status, source) VALUES
('Pacific Rim Manufacturing', 'business', 'chapter_11', 'Manufacturing', 'CNC machining and precision parts manufacturer with $18M annual revenue.', 32000000, 22000000, 0.31, 'Long Beach', 'CA', 'active', 'Court Filing'),
('Heartland Retail Group', 'business', 'chapter_11', 'Retail', 'Regional department store chain with 12 locations and owned real estate.', 45000000, 28000000, 0.38, 'Indianapolis', 'IN', 'active', 'Court Filing'),
('Southeastern Healthcare Systems', 'business', 'receivership', 'Healthcare', 'Multi-facility urgent care chain with 8 locations and $25M revenue.', 40000000, 26000000, 0.35, 'Charlotte', 'NC', 'active', 'Receiver Sale'),
('Rocky Mountain Energy Corp', 'business', 'chapter_11', 'Energy', 'Natural gas production company with proven reserves and pipeline access.', 85000000, 52000000, 0.39, 'Denver', 'CO', 'active', 'Court Filing'),
('Great Lakes Shipping Co', 'business', 'chapter_7', 'Logistics', 'Bulk cargo shipping fleet with 6 vessels on the Great Lakes.', 28000000, 15000000, 0.46, 'Cleveland', 'OH', 'active', 'Trustee Sale'),
('Southwest Restaurant Holdings', 'business', 'foreclosure', 'Food Service', 'Casual dining chain with 22 owned locations across TX, AZ, NM.', 55000000, 35000000, 0.36, 'Phoenix', 'AZ', 'active', 'Bank Sale'),
('Atlantic Print Media', 'business', 'chapter_11', 'Media', 'Regional newspaper and digital media company with 500K subscribers.', 18000000, 10000000, 0.44, 'Baltimore', 'MD', 'active', 'Court Filing'),
('Cascade Timber Holdings', 'business', 'receivership', 'Forestry', 'Timberland holdings with 50K acres and sawmill operations.', 75000000, 48000000, 0.36, 'Eugene', 'OR', 'active', 'Receiver Sale'),
('Gulf Coast Marine Services', 'business', 'chapter_11', 'Maritime', 'Offshore support vessel company serving oil and gas platforms.', 120000000, 65000000, 0.46, 'Houston', 'TX', 'active', 'Court Filing'),
('Prairie Wind Farms LLC', 'business', 'tax_lien', 'Energy', 'Wind farm portfolio with 200MW installed capacity across 3 sites.', 180000000, 120000000, 0.33, 'Oklahoma City', 'OK', 'active', 'Tax Sale'),
('Midwest Auto Parts Dist', 'business', 'assignment_for_benefit', 'Automotive', 'Aftermarket auto parts distribution network with 15 warehouses.', 35000000, 22000000, 0.37, 'Detroit', 'MI', 'active', 'ABC Sale'),
('Silicon Beach Software', 'ip_portfolio', 'chapter_7', 'Technology', 'Patent portfolio covering 12 patents in machine learning and NLP.', 8000000, 4500000, 0.44, 'Santa Monica', 'CA', 'active', 'Trustee Sale'),
('Appalachian Coal Assets', 'equipment', 'chapter_11', 'Mining', 'Underground mining equipment and mineral rights on 10K acres.', 45000000, 25000000, 0.44, 'Charleston', 'WV', 'active', 'Court Filing'),
('Northeast Cold Storage', 'business', 'foreclosure', 'Logistics', 'Temperature-controlled warehouse network with 2M sq ft capacity.', 65000000, 42000000, 0.35, 'Newark', 'NJ', 'active', 'Bank Sale'),
('SunState Hotel Group', 'business', 'receivership', 'Hospitality', 'Portfolio of 8 limited-service hotels totaling 900 rooms.', 90000000, 55000000, 0.39, 'Orlando', 'FL', 'active', 'Receiver Sale'),
('Metro Fitness Centers', 'business', 'chapter_11', 'Fitness', 'Chain of 15 fitness centers with long-term lease commitments.', 22000000, 12000000, 0.45, 'Philadelphia', 'PA', 'active', 'Court Filing'),
('Pioneer Aerospace Parts', 'inventory', 'chapter_7', 'Aerospace', 'FAA-certified aerospace parts inventory valued at replacement cost.', 15000000, 8000000, 0.47, 'Wichita', 'KS', 'active', 'Trustee Sale'),
('Bayou Chemical Processing', 'business', 'chapter_11', 'Chemicals', 'Specialty chemical manufacturing facility with EPA permits.', 55000000, 35000000, 0.36, 'Baton Rouge', 'LA', 'active', 'Court Filing'),
('Mountain View Senior Living', 'business', 'receivership', 'Healthcare', 'Senior living portfolio with 3 facilities and 450 beds.', 72000000, 45000000, 0.38, 'Tucson', 'AZ', 'active', 'Receiver Sale'),
('Liberty Telecom', 'business', 'chapter_11', 'Telecom', 'Rural fiber-optic internet provider serving 25K subscribers.', 38000000, 24000000, 0.37, 'Des Moines', 'IA', 'active', 'Court Filing'),
('Golden State Produce', 'business', 'assignment_for_benefit', 'Agriculture', 'Fresh produce distribution company with cold chain network.', 28000000, 18000000, 0.36, 'Fresno', 'CA', 'active', 'ABC Sale'),
('Heritage Furniture Mfg', 'business', 'chapter_7', 'Manufacturing', 'Custom furniture manufacturer with CNC equipment and showroom.', 12000000, 6500000, 0.46, 'High Point', 'NC', 'active', 'Trustee Sale'),
('TechBridge Solutions IP', 'ip_portfolio', 'chapter_11', 'Technology', 'SaaS patent portfolio with 8 active patents in cloud computing.', 12000000, 7000000, 0.42, 'Reston', 'VA', 'active', 'Court Filing'),
('Sunbelt Construction Group', 'business', 'foreclosure', 'Construction', 'Commercial general contractor with $50M backlog and equipment fleet.', 35000000, 22000000, 0.37, 'Atlanta', 'GA', 'active', 'Bank Sale'),
('Lake Michigan Marina', 'business', 'tax_lien', 'Maritime', 'Full-service marina with 300 slips and waterfront restaurant.', 25000000, 16000000, 0.36, 'Milwaukee', 'WI', 'active', 'Tax Sale'),
('Pacific NW Lumber', 'business', 'chapter_11', 'Forestry', 'Lumber mill and distribution with Pacific Northwest timber access.', 42000000, 27000000, 0.36, 'Tacoma', 'WA', 'active', 'Court Filing'),
('Garden State Pharma', 'business', 'receivership', 'Pharma', 'Generic pharmaceutical manufacturer with FDA-approved facility.', 65000000, 40000000, 0.38, 'Princeton', 'NJ', 'active', 'Receiver Sale'),
('Delta Agriculture Holdings', 'business', 'chapter_11', 'Agriculture', 'Row crop farming operation with 15K irrigated acres in MS Delta.', 50000000, 32000000, 0.36, 'Greenville', 'MS', 'active', 'Court Filing'),
('Cascadia Brewery Group', 'business', 'assignment_for_benefit', 'Beverage', 'Craft brewery portfolio with 4 taprooms and distribution in 5 states.', 18000000, 10000000, 0.44, 'Portland', 'OR', 'active', 'ABC Sale'),
('Empire State Logistics', 'business', 'chapter_11', 'Logistics', 'Regional LTL carrier with 200-truck fleet and terminal network.', 45000000, 28000000, 0.38, 'Syracuse', 'NY', 'active', 'Court Filing'),
('Lone Star Oil Services', 'equipment', 'foreclosure', 'Energy', 'Oilfield services equipment fleet including workover rigs and pumps.', 30000000, 17000000, 0.43, 'Midland', 'TX', 'active', 'Bank Sale'),
('Coastal Defense Systems', 'ip_portfolio', 'chapter_7', 'Defense', 'Defense technology patents covering radar and communications.', 20000000, 11000000, 0.45, 'San Diego', 'CA', 'active', 'Trustee Sale'),
('Heartland Ethanol', 'business', 'chapter_11', 'Energy', 'Corn ethanol production facility with 100M gallon annual capacity.', 95000000, 55000000, 0.42, 'Sioux Falls', 'SD', 'active', 'Court Filing'),
('Metro Dental Group', 'business', 'receivership', 'Healthcare', 'Multi-location dental practice group with 20 offices.', 25000000, 16000000, 0.36, 'Las Vegas', 'NV', 'active', 'Receiver Sale'),
('Skyline Aviation', 'equipment', 'chapter_7', 'Aviation', 'Regional airline aircraft fleet of 8 turboprops.', 35000000, 18000000, 0.49, 'Albuquerque', 'NM', 'active', 'Trustee Sale'),
('Valley Ag Equipment', 'equipment', 'tax_lien', 'Agriculture', 'Farm equipment dealership inventory and service operation.', 12000000, 7500000, 0.38, 'Boise', 'ID', 'active', 'Tax Sale'),
('Columbia River Seafood', 'business', 'chapter_11', 'Food', 'Seafood processing and distribution with Pacific fleet access.', 38000000, 24000000, 0.37, 'Astoria', 'OR', 'active', 'Court Filing'),
('Dixie Textile Mills', 'business', 'chapter_7', 'Textiles', 'Cotton textile manufacturing with modernized spinning equipment.', 20000000, 10000000, 0.50, 'Greenville', 'SC', 'active', 'Trustee Sale'),
('Tidewater Marine Repair', 'business', 'foreclosure', 'Maritime', 'Ship repair and drydock facility with deepwater access.', 42000000, 27000000, 0.36, 'Norfolk', 'VA', 'active', 'Bank Sale'),
('Prairie Healthcare Network', 'business', 'chapter_11', 'Healthcare', 'Rural hospital and clinic network serving 5-county area.', 85000000, 50000000, 0.41, 'Rapid City', 'SD', 'active', 'Court Filing'),
-- Loan portfolios and other asset types
('Consumer Loan Portfolio 2024-A', 'loan_portfolio', 'voluntary_sale', 'Financial Services', 'Performing consumer loan portfolio with 5.2% weighted avg coupon.', 150000000, 135000000, 0.10, 'New York', 'NY', 'active', 'Broker Sale'),
('CRE Loan Portfolio Midwest', 'loan_portfolio', 'voluntary_sale', 'Real Estate', 'Mixed CRE loan portfolio with 85% performing loans.', 200000000, 160000000, 0.20, 'Chicago', 'IL', 'active', 'Broker Sale'),
('Auto Loan Portfolio SE', 'loan_portfolio', 'chapter_7', 'Financial Services', 'Sub-prime auto loan portfolio with 8.5% yield.', 75000000, 52000000, 0.31, 'Atlanta', 'GA', 'active', 'Trustee Sale'),
('SBA Loan Portfolio', 'loan_portfolio', 'voluntary_sale', 'Financial Services', 'SBA 7(a) loan portfolio with government guarantee.', 45000000, 42000000, 0.07, 'Washington DC', 'DC', 'active', 'Broker Sale'),
('Student Housing Loan Pool', 'loan_portfolio', 'receivership', 'Real Estate', 'Student housing CMBS loans across 6 university markets.', 120000000, 85000000, 0.29, 'Boston', 'MA', 'active', 'Receiver Sale'),
('Hospitality Mortgage Pool', 'loan_portfolio', 'chapter_11', 'Hospitality', 'Hotel mortgage loans with 60% weighted LTV.', 180000000, 125000000, 0.31, 'Miami', 'FL', 'active', 'Court Filing'),
('Semiconductor IP Bundle', 'ip_portfolio', 'chapter_7', 'Technology', 'Semiconductor process patents covering 3nm and below.', 50000000, 28000000, 0.44, 'San Jose', 'CA', 'active', 'Trustee Sale'),
('Wireless Tech Patents', 'ip_portfolio', 'chapter_11', 'Telecom', '5G and IoT patent portfolio with 25 active patents.', 35000000, 20000000, 0.43, 'Dallas', 'TX', 'active', 'Court Filing'),
('Medical Device IP', 'ip_portfolio', 'assignment_for_benefit', 'Healthcare', 'Surgical robotics patents and trade secrets.', 40000000, 25000000, 0.38, 'Minneapolis', 'MN', 'active', 'ABC Sale'),
('EV Battery Tech IP', 'ip_portfolio', 'chapter_7', 'Automotive', 'Solid-state battery patents with pending applications.', 60000000, 35000000, 0.42, 'Detroit', 'MI', 'active', 'Trustee Sale');
