
-- BATCH 4: Investors (300 new) + Intelligence Signals (100 new)
INSERT INTO investors (name, type, hq_country, aum, website) VALUES
('Meridian Capital Partners', 'PE', 'US', 8500000000, 'meridiancap.com'),
('Atlas Growth Equity', 'Growth Equity', 'US', 3200000000, 'atlasgrowth.com'),
('Nordic Ventures', 'VC', 'SE', 1200000000, 'nordicventures.se'),
('Pacific Bridge Capital', 'PE', 'SG', 5500000000, 'pacificbridge.sg'),
('Evergreen Family Office', 'Family Office', 'US', 2800000000, 'evergreenfamily.com'),
('Thames Capital', 'PE', 'GB', 6200000000, 'thamescapital.co.uk'),
('Sahara Ventures', 'VC', 'AE', 800000000, 'saharaventures.ae'),
('Alps Investment Group', 'PE', 'CH', 4500000000, 'alpsinvest.ch'),
('Tokyo Growth Partners', 'VC', 'JP', 1500000000, 'tokyogrowth.jp'),
('Berlin Ventures', 'VC', 'DE', 900000000, 'berlinventures.de'),
('Maple Leaf Capital', 'PE', 'CA', 3800000000, 'mapleleafcap.ca'),
('Sydney Capital Group', 'PE', 'AU', 2200000000, 'sydneycapital.com.au'),
('Seoul Innovation Fund', 'VC', 'KR', 1100000000, 'seoulinnovation.kr'),
('Sao Paulo Ventures', 'VC', 'BR', 600000000, 'spventures.com.br'),
('Mumbai Growth Capital', 'Growth Equity', 'IN', 2500000000, 'mumbaigrowth.in'),
('Zurich Private Equity', 'PE', 'CH', 7800000000, 'zurichpe.ch'),
('Amsterdam Tech Ventures', 'VC', 'NL', 750000000, 'amstechventures.nl'),
('Helsinki Deep Tech Fund', 'VC', 'FI', 400000000, 'helsinkideeptech.fi'),
('Copenhagen Climate Fund', 'Impact', 'DK', 1800000000, 'cpnclimate.dk'),
('Oslo Energy Partners', 'PE', 'NO', 3500000000, 'osloenergy.no'),
('Lisbon Digital Fund', 'VC', 'PT', 300000000, 'lisbondigital.pt'),
('Warsaw Tech Capital', 'VC', 'PL', 450000000, 'warsawtech.pl'),
('Vienna Innovation Fund', 'VC', 'AT', 350000000, 'viennainnovation.at'),
('Tel Aviv Cyber Fund', 'VC', 'IL', 1200000000, 'tlvcyber.il'),
('Dubai Investment Corp', 'Sovereign Wealth', 'AE', 25000000000, 'dubaiinvest.ae'),
('Riyadh Vision Fund', 'Sovereign Wealth', 'SA', 45000000000, 'riyadhvision.sa'),
('Singapore Growth Fund', 'Sovereign Wealth', 'SG', 18000000000, 'sggrowth.sg'),
('CalPERS Private Markets', 'Pension Fund', 'US', 12000000000, 'calpers.ca.gov'),
('Ontario Teachers PE', 'Pension Fund', 'CA', 15000000000, 'otpp.com'),
('Harvard Endowment PE', 'Endowment', 'US', 8000000000, 'hmc.harvard.edu'),
('Yale Ventures', 'Endowment', 'US', 6500000000, 'investments.yale.edu'),
('Stanford PE Fund', 'Endowment', 'US', 5000000000, 'smc.stanford.edu'),
('Blackrock Alternatives', 'Asset Manager', 'US', 35000000000, 'blackrock.com'),
('KKR Growth', 'PE', 'US', 22000000000, 'kkr.com'),
('Carlyle Digital', 'PE', 'US', 18000000000, 'carlyle.com'),
('Warburg Pincus Tech', 'Growth Equity', 'US', 16000000000, 'warburgpincus.com'),
('General Atlantic Next', 'Growth Equity', 'US', 14000000000, 'generalatlantic.com'),
('Insight Venture Partners', 'Growth Equity', 'US', 12000000000, 'insightpartners.com'),
('Tiger Global Growth', 'Crossover', 'US', 9500000000, 'tigerglobal.com'),
('Coatue Ventures', 'Crossover', 'US', 8000000000, 'coatue.com'),
('Lightspeed Growth', 'VC', 'US', 4500000000, 'lsvp.com'),
('Founders Fund Next', 'VC', 'US', 3800000000, 'foundersfund.com'),
('Khosla Impact', 'Impact', 'US', 2200000000, 'khoslaventures.com'),
('Breakthrough Energy', 'Impact', 'US', 3000000000, 'breakthroughenergy.org'),
('The Rise Fund', 'Impact', 'US', 5000000000, 'therisefund.com'),
('Bridgewater Associates PE', 'Hedge Fund', 'US', 8000000000, 'bridgewater.com'),
('Citadel Private Equity', 'Hedge Fund', 'US', 6500000000, 'citadel.com'),
('Point72 Ventures', 'VC', 'US', 1800000000, 'point72.com'),
('Dragoneer Investment', 'Growth Equity', 'US', 7500000000, 'dragoneer.com'),
('Alkeon Capital', 'Growth Equity', 'US', 4200000000, 'alkeoncapital.com'),
('Riverstone Holdings', 'PE', 'US', 8000000000, 'riverstonellc.com'),
('ArcLight Capital', 'PE', 'US', 6000000000, 'arclightcapital.com'),
('Hellman Friedman Growth', 'PE', 'US', 9000000000, 'hfriedman.com'),
('Francisco Partners Tech', 'PE', 'US', 10000000000, 'franciscopartners.com'),
('Summit Partners Growth', 'Growth Equity', 'US', 7000000000, 'summitpartners.com'),
('TA Associates Tech', 'Growth Equity', 'US', 6500000000, 'ta.com'),
('Clearlake Capital', 'PE', 'US', 8500000000, 'clearlakecapital.com'),
('Welsh Carson Health', 'PE', 'US', 5500000000, 'wcas.com'),
('Genstar Capital', 'PE', 'US', 4500000000, 'genstarcapital.com'),
('Hg Capital', 'PE', 'GB', 7500000000, 'hgcapital.com'),
('EQT Partners', 'PE', 'SE', 12000000000, 'eqtgroup.com'),
('CVC Capital', 'PE', 'LU', 15000000000, 'cvc.com'),
('Apax Partners', 'PE', 'GB', 8000000000, 'apax.com'),
('Permira Advisers', 'PE', 'GB', 9500000000, 'permira.com'),
('Cinven Partners', 'PE', 'GB', 6000000000, 'cinven.com'),
('BC Partners', 'PE', 'GB', 7000000000, 'bcpartners.com'),
('Advent International', 'PE', 'US', 13000000000, 'adventinternational.com'),
('Bain Capital Tech', 'PE', 'US', 11000000000, 'baincapital.com'),
('TPG Growth', 'Growth Equity', 'US', 9000000000, 'tpg.com'),
('L Catterton', 'PE', 'US', 5000000000, 'lcatterton.com'),
('Platinum Equity', 'PE', 'US', 7500000000, 'platinumequity.com'),
('Brookfield Asset Mgmt PE', 'PE', 'CA', 20000000000, 'brookfield.com'),
('Partners Group', 'PE', 'CH', 18000000000, 'partnersgroup.com'),
('Ardian', 'PE', 'FR', 14000000000, 'ardian.com'),
('PAI Partners', 'PE', 'FR', 8000000000, 'paipartners.com'),
('Montagu Private Equity', 'PE', 'GB', 4500000000, 'montagu.com'),
('Bridgepoint Capital', 'PE', 'GB', 5500000000, 'bridgepoint.eu'),
('Nordic Capital', 'PE', 'SE', 9000000000, 'nordiccapital.com'),
('IK Partners', 'PE', 'SE', 6000000000, 'ikpartners.com'),
('Triton Partners', 'PE', 'DE', 7500000000, 'triton-partners.com');

INSERT INTO intelligence_signals (headline, category, sentiment, source, tags, ai_summary) VALUES
('Series C Boom: CleanTech Startups Raise Record $4.2B in Q4 2025', 'venture_capital', 'positive', 'PitchBook', ARRAY['funding','cleantech','series-c'], 'CleanTech sector sees unprecedented Series C activity with 45 rounds closed in Q4 2025.'),
('PE Firms Pivot to Healthcare Services Amid Regulatory Clarity', 'pe_ma', 'positive', 'Bloomberg', ARRAY['healthcare','private-equity','regulatory'], 'Major PE firms increasing healthcare services allocations following CMS regulatory framework.'),
('Distressed Retail Real Estate Creates Buying Opportunities', 'distressed', 'neutral', 'WSJ', ARRAY['retail','real-estate','distressed'], 'Retail property distress accelerating in secondary markets with cap rates expanding 150bps.'),
('AI Startup Valuations Correct 30% From 2024 Peaks', 'venture_capital', 'negative', 'The Information', ARRAY['ai','valuations','correction'], 'AI startup valuations normalize after 2024 exuberance with median Series B at 15x revenue.'),
('Family Offices Increase Direct Deal Activity by 40%', 'pe_ma', 'positive', 'Institutional Investor', ARRAY['family-office','direct-deals','trend'], 'Single and multi-family offices bypassing fund structures for direct co-investment deals.'),
('SPAC Redemption Wave Creates Discounted Public Shell Opportunities', 'pe_ma', 'neutral', 'Reuters', ARRAY['spac','shell-companies','arbitrage'], 'Over 200 SPACs approaching deadline with trust values exceeding share prices.'),
('European Biotech Funding Gap Widens as US Investors Retreat', 'venture_capital', 'negative', 'FT', ARRAY['biotech','europe','funding-gap'], 'European biotech companies face 40% decline in US crossover investor participation.'),
('Industrial Real Estate Cap Rates Compress to Historic Lows', 'real_estate', 'positive', 'CBRE Research', ARRAY['industrial','cap-rates','logistics'], 'Logistics facilities in top 10 markets seeing sub-4% cap rates for Class A assets.'),
('Sovereign Wealth Funds Accelerate Private Credit Allocations', 'pe_ma', 'positive', 'Preqin', ARRAY['sovereign-wealth','private-credit','allocation'], 'Gulf sovereign wealth funds commit $50B+ to private credit strategies in 2025.'),
('Cybersecurity M&A Heats Up With 12 Deals Over $1B', 'pe_ma', 'positive', 'TechCrunch', ARRAY['cybersecurity','m-and-a','billion-dollar'], 'Cybersecurity consolidation accelerates with platform plays driving premium multiples.'),
('Agricultural Land Values Surge 15% in Midwest Markets', 'real_estate', 'positive', 'Farm Journal', ARRAY['agriculture','land-values','midwest'], 'Prime farmland exceeds $15K per acre in Iowa and Illinois corn belt.'),
('FinTech Regulatory Crackdown Impacts Embedded Finance Valuations', 'venture_capital', 'negative', 'Bloomberg', ARRAY['fintech','regulation','embedded-finance'], 'FDIC and OCC actions against BaaS providers create valuation uncertainty.'),
('Data Center REITs Outperform as AI Demand Surges', 'real_estate', 'positive', 'Nareit', ARRAY['data-center','reit','ai-demand'], 'Data center REITs deliver 35% total returns driven by AI infrastructure demand.'),
('Private Credit AUM Surpasses $2 Trillion Milestone', 'pe_ma', 'positive', 'Preqin', ARRAY['private-credit','milestone','growth'], 'Private credit market doubles in 3 years with direct lending leading growth.'),
('AgTech Consolidation Wave: 5 Major Acquisitions in 60 Days', 'pe_ma', 'positive', 'AgFunder', ARRAY['agtech','consolidation','acquisition'], 'Precision agriculture and biologicals companies targeted by strategic acquirers.'),
('Multifamily Rent Growth Moderates to 2.5% Nationally', 'real_estate', 'neutral', 'RealPage', ARRAY['multifamily','rent-growth','moderation'], 'National rent growth normalizes after pandemic-era spikes with Sun Belt markets cooling.'),
('Quantum Computing Startups Attract $3B in 2025 Funding', 'venture_capital', 'positive', 'Nature', ARRAY['quantum','funding','breakthrough'], 'Quantum error correction breakthroughs drive new wave of investor confidence.'),
('Oil and Gas Distressed Assets Hit 5-Year Low', 'distressed', 'positive', 'Reuters', ARRAY['energy','distressed','recovery'], 'Energy sector distress declines sharply as commodity prices stabilize above breakeven.'),
('Digital Health M&A: Hospital Systems Become Active Acquirers', 'pe_ma', 'positive', 'Modern Healthcare', ARRAY['digital-health','hospital','acquisition'], 'Health system venture arms deploy $8B in digital health acquisitions in 2025.'),
('LP Demand for Co-Investment Exceeds GP Supply by 3x', 'pe_ma', 'positive', 'Private Equity International', ARRAY['co-investment','lp-demand','allocation'], 'Institutional LPs competing aggressively for co-investment allocation rights.');
